[functions]
  included_files = ["public/locales/**/*.json", "next-i18next.config.js"]

[[plugins]]
  package = "@commercetools/frontend-netlify-plugin"

[build]
  ignore = "$CACHED_COMMIT_REF == $COMMIT_REF"